# Generated by Django 2.0 on 2019-03-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runtype',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.Project'),
            preserve_default=False,
        ),
    ]
