# Generated by Django 2.0 on 2019-03-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190312_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=100, verbose_name='部门(英文)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(default='', max_length=100, verbose_name='部门(中文)'),
        ),
        migrations.AlterField(
            model_name='env',
            name='env',
            field=models.CharField(max_length=100, verbose_name='环境(英文)'),
        ),
        migrations.AlterField(
            model_name='env',
            name='envName',
            field=models.CharField(default='', max_length=100, verbose_name='环境(中文)'),
        ),
        migrations.AlterField(
            model_name='env',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(max_length=100, verbose_name='项目(英文)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(default='', max_length=100, verbose_name='项目(中文)'),
        ),
        migrations.AlterField(
            model_name='runtype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project', verbose_name='所属项目'),
        ),
    ]
