# Generated by Django 2.0 on 2019-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190312_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='baseUrl',
            field=models.URLField(default='', verbose_name='默认链接'),
        ),
        migrations.AddField(
            model_name='runtype',
            name='runTypeName',
            field=models.CharField(max_length=100, null=True, verbose_name='执行类型(中文)'),
        ),
        migrations.AlterField(
            model_name='runtype',
            name='runType',
            field=models.CharField(max_length=100, null=True, verbose_name='执行类型(英文)'),
        ),
    ]
