# Generated by Django 2.0 on 2019-03-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190313_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platformName',
            field=models.CharField(default='', max_length=20, verbose_name='运行平台(中文)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform',
            field=models.CharField(max_length=20, verbose_name='运行平台(英文)'),
        ),
    ]
