# Generated by Django 2.0 on 2019-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190313_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=100, verbose_name='部门(部门用例库根文件名)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(max_length=100, verbose_name="项目(项目用例库根文件名)'"),
        ),
    ]
