# Generated by Django 2.0 on 2019-03-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20190314_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.FileField(null=True, upload_to='yaml/tmp', verbose_name='用例文件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
    ]
