# Generated by Django 2.0 on 2019-03-18 14:51

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='projectName',
            field=models.CharField(max_length=100, null=True, verbose_name='项目路径'),
        ),
        migrations.AlterField(
            model_name='case',
            name='caseName',
            field=models.FileField(null=True, upload_to=organization.models.upload_to, verbose_name='用例文件'),
        ),
    ]
