# Generated by Django 2.0 on 2019-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20190318_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='projectName',
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=100, verbose_name='部门(英文)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(max_length=100, verbose_name='项目(英文)'),
        ),
    ]
