#!/bin/bash

#application settings
#export DJANGO_SETTINGS_MODULE=autoCN.settings
cd /home/docker/code/
./manage.py migrate --noinput
./manage.py loaddata ./fixtures/superuser.json
./manage.py collectstatic --noinput