# Generated by Django 2.1.3 on 2018-11-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(verbose_name='成功用例數')),
                ('stat_testsRun', models.IntegerField(verbose_name='執行用例數')),
                ('stat_successes', models.IntegerField(verbose_name='成功用例數')),
                ('stat_failures', models.IntegerField(verbose_name='失敗用例數')),
                ('stat_errors', models.IntegerField(verbose_name='Error用例數')),
                ('stat_skipped', models.IntegerField(verbose_name='跳過用例數')),
                ('start_datetime', models.DateTimeField(verbose_name='開始時間')),
                ('duration', models.FloatField(verbose_name='耗時')),
                ('httpRunner_version', models.CharField(max_length=40, verbose_name='HttpRunner版本')),
                ('python_version', models.CharField(max_length=20, verbose_name='python版本')),
                ('platform', models.CharField(max_length=60, verbose_name='系統平臺')),
                ('details', models.TextField(verbose_name='執行結果')),
                ('notes', models.TextField(verbose_name='備註')),
                ('env', models.CharField(max_length=30, verbose_name='測試環境')),
            ],
            options={
                'verbose_name': '測試執行結果',
                'db_table': 'CaseResult',
            },
        ),
    ]
