# Generated by Django 2.0 on 2018-12-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseresult',
            old_name='reports',
            new_name='case_reports',
        ),
    ]
