# Generated by Django 2.1.3 on 2018-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='env',
            field=models.CharField(max_length=30, null=True, verbose_name='測試環境'),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='notes',
            field=models.TextField(null=True, verbose_name='備註'),
        ),
    ]
