# Generated by Django 2.0 on 2018-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0002_auto_20181210_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetail',
            name='case_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
