# Generated by Django 2.0 on 2018-12-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0003_casedetail_case_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseresult',
            name='caseDetails',
        ),
        migrations.AddField(
            model_name='casedetail',
            name='caseResult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoApi.CaseResult'),
        ),
    ]
