# Generated by Django 2.1.3 on 2018-11-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0004_auto_20181108_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='start_datetime',
            field=models.FloatField(verbose_name='開始時間'),
        ),
    ]
