# Generated by Django 2.0 on 2018-12-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0004_auto_20181210_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='case_reports',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoApi.HtmlReport'),
        ),
    ]
