# Generated by Django 2.1.3 on 2018-11-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0005_auto_20181109_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='start_datetime',
            field=models.CharField(max_length=40, verbose_name='開始時間'),
        ),
    ]
