# Generated by Django 2.0 on 2018-12-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0005_auto_20181211_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesCategory', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'notesCategory',
                'db_table': 'notesCategory',
            },
        ),
        migrations.AddField(
            model_name='caseresult',
            name='notesCategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoApi.notesCategory'),
        ),
    ]
