# Generated by Django 2.0 on 2018-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0006_auto_20181214_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='notesCategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
