# Generated by Django 2.0 on 2018-12-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0007_auto_20181214_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='passrate',
            field=models.FloatField(null=True, verbose_name='通过率'),
        ),
    ]
