# Generated by Django 2.0 on 2018-12-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0008_caseresult_passrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresult',
            name='runType',
            field=models.IntegerField(default='1', null=True, verbose_name='执行类型'),
        ),
    ]
