# Generated by Django 2.0 on 2019-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0010_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetail',
            name='department',
            field=models.CharField(choices=[('newCar', '新车'), ('usedCar', '中古车')], default='', max_length=10, verbose_name='部门'),
        ),
    ]
