# Generated by Django 2.0 on 2019-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0012_casedetail_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='aritcleDescription',
            field=models.TextField(null=True, verbose_name='文章简述'),
        ),
    ]
