# Generated by Django 2.0 on 2019-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0014_auto_20190111_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('H5', '触屏'), ('PC', 'PC')], max_length=10, verbose_name='平台'),
        ),
    ]
