# Generated by Django 2.0 on 2019-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0015_auto_20190213_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Env',
                'db_table': 'Env',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Platform',
                'db_table': 'Platform',
            },
        ),
    ]
