# Generated by Django 2.0 on 2019-02-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0016_env_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='envName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='platform',
            name='platformName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
