# Generated by Django 2.0 on 2019-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0017_auto_20190213_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('departmentName', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'db_table': 'Department',
            },
        ),
    ]
