# Generated by Django 2.0 on 2019-02-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0018_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseresult',
            name='env',
        ),
        migrations.RemoveField(
            model_name='caseresult',
            name='platform',
        ),
        migrations.AddField(
            model_name='env',
            name='caseResult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoApi.CaseResult'),
        ),
        migrations.AddField(
            model_name='platform',
            name='caseResult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoApi.CaseResult'),
        ),
    ]
