# Generated by Django 2.0 on 2019-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0019_auto_20190213_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='caseResult',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='caseResult',
        ),
        migrations.AddField(
            model_name='caseresult',
            name='env',
            field=models.CharField(default='testEnv', max_length=30, null=True, verbose_name='測試環境'),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android'), ('H5', '触屏'), ('PC', 'PC')], default='PC', max_length=10, verbose_name='平台'),
        ),
    ]
