# Generated by Django 2.0 on 2019-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0021_auto_20190214_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentName',
            new_name='departmentCn',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='departmentEn',
        ),
        migrations.RenameField(
            model_name='env',
            old_name='envName',
            new_name='envCn',
        ),
        migrations.RenameField(
            model_name='env',
            old_name='env',
            new_name='envEn',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platformName',
        ),
        migrations.AddField(
            model_name='platform',
            name='platformEn',
            field=models.CharField(default='PC', max_length=20, verbose_name='平台'),
        ),
    ]
