# Generated by Django 2.0 on 2019-02-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0022_auto_20190220_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentEn',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='env',
            old_name='envEn',
            new_name='env',
        ),
    ]
