# Generated by Django 2.0 on 2019-02-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0024_auto_20190220_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentCn',
            new_name='departmentName',
        ),
    ]
