# Generated by Django 2.0 on 2019-02-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0025_auto_20190220_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='env',
            old_name='envCn',
            new_name='envName',
        ),
    ]
