# Generated by Django 2.0 on 2019-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0026_auto_20190220_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runType', models.CharField(default='手动执行', max_length=25, null=True, verbose_name='执行类型')),
            ],
            options={
                'verbose_name': 'RunType',
                'db_table': 'RunType',
            },
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='runType',
            field=models.CharField(default='手动执行', max_length=25, null=True, verbose_name='执行类型'),
        ),
    ]
