# Generated by Django 2.0 on 2019-02-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0027_auto_20190220_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章管理', 'verbose_name_plural': '文章管理'},
        ),
        migrations.AlterModelOptions(
            name='casedetail',
            options={'verbose_name': '用例详情', 'verbose_name_plural': '用例详情'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门管理', 'verbose_name_plural': '部门管理'},
        ),
        migrations.AlterModelOptions(
            name='env',
            options={'verbose_name': '环境管理', 'verbose_name_plural': '环境管理'},
        ),
        migrations.AlterModelOptions(
            name='htmlreport',
            options={'verbose_name': '测试报告', 'verbose_name_plural': '测试报告'},
        ),
        migrations.AlterModelOptions(
            name='notescategory',
            options={'verbose_name': '备注类别', 'verbose_name_plural': '备注类别'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': '平台管理', 'verbose_name_plural': '平台管理'},
        ),
        migrations.AlterModelOptions(
            name='runtype',
            options={'verbose_name': '执行方式', 'verbose_name_plural': '执行方式'},
        ),
    ]
