# Generated by Django 2.0 on 2019-02-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0028_auto_20190220_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casedetail',
            options={'verbose_name': '执行详情', 'verbose_name_plural': '执行详情'},
        ),
        migrations.AlterModelOptions(
            name='caseresult',
            options={'verbose_name': '執行結果', 'verbose_name_plural': '執行結果'},
        ),
    ]
