# Generated by Django 2.0 on 2019-03-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0002_auto_20190312_1131'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casedetail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='caseresult',
            table=None,
        ),
        migrations.AlterModelTable(
            name='htmlreport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notescategory',
            table=None,
        ),
    ]
