# Generated by Django 2.0 on 2019-03-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0003_auto_20190312_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetail',
            name='project',
            field=models.CharField(default='', max_length=30, verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='caseresult',
            name='project',
            field=models.CharField(default='', max_length=30, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='department',
            field=models.CharField(default='', max_length=30, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='env',
            field=models.CharField(max_length=30, null=True, verbose_name='测试环境'),
        ),
        migrations.AlterField(
            model_name='caseresult',
            name='department',
            field=models.CharField(default='', max_length=10, verbose_name='部门'),
        ),
    ]
