# Generated by Django 2.0 on 2019-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0004_auto_20190312_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notescategory',
            name='notesCategory',
            field=models.CharField(max_length=100, verbose_name='备注类别 '),
        ),
    ]
