# Generated by Django 2.0 on 2019-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoApi', '0007_auto_20190318_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseresult',
            name='cookie',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='cookie'),
        ),
    ]
