# Generated by Django 2.0 on 2019-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190312_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jobnumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
