# Generated by Django 2.0 on 2019-03-12 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleName', models.CharField(max_length=50, verbose_name='文章标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间 ')),
                ('aritcleDescription', models.TextField(null=True, verbose_name='文章简述')),
                ('aritcleContent', models.TextField(verbose_name='文章内容')),
                ('articleImg', models.ImageField(upload_to='static/img/%Y/%m', verbose_name='封面图')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'db_table': 'Article',
            },
        ),
    ]
