# Generated by Django 2.0 on 2019-03-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
