# Generated by Django 2.0 on 2019-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190312_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleImg',
            field=models.ImageField(upload_to='static/img/system/%Y/%m', verbose_name='封面图'),
        ),
    ]
